### PR TITLE
Create funcionality for user recovery password

### PR DESCRIPTION
**Pull request by matvaleriano**
Issue #8 

- fix invalid attribute error of formFeedback
- create pages (recovery and reset password)
- include routes for pages

I tried to keep the project code pattern.

### CODE REVIEW

**Comment by matvaleriano** [comment]
I dont know what the pattern is with the quotation marks. In parts have single quotes and in other parts have double quotes.

**Comment by alexanmtz** [comment]
Don’t worry about the other quotes, leave in single quotes that will be the
default

**Comment by matvaleriano** [comment]
ok, but it will not pass in the quality review.

**Review by alexanmtz — APPROVED** [review]
Great @mathvaleriano, thanks and we will implement some code standards to allow a better validation about the rules, thanks for the feedback

**Pull request merged**
